export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';
export const GET_PROFILES = 'GET_PROFILES';
